version: 3.0.0-alpha-{build}
os: Visual Studio 2017
configuration: Release
environment:
  FRAMEWORK: netcoreapp2.0
  matrix:
    - RUNTIME: win-x86      	
    - RUNTIME: linux-x64
    - RUNTIME: osx-x64
assembly_info:
  patch: true
  file: '**\SolutionInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
install:
- cmd: |
    dotnet restore
    npm install -g gulp bower
build_script:
 - cmd: dotnet build Rnwood.Smtp4dev.sln -c %Configuration%
after_build:
 - ps: |
    $versionsuffix=$("{0:D4}" -f [convert]::ToInt32($env:APPVEYOR_BUILD_NUMBER, 10))
    dotnet publish Rnwood.Smtp4dev -c $env:Configuration -f $env:FRAMEWORK -r $env:RUNTIME  --version-suffix $versionsuffix
build:
  publish_nuget: false
  publish_nuget_symbols: false
  parallel: true
  verbosity: minimal
artifacts:
- path: Rnwood.Smtp4dev\bin\$(configuration)\$(framework)\$(runtime)\publish
  name: Smtp4dev-$(runtime)-v$(appveyor_build_version)
  type: zip